[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -D CORE_DEBUG_LEVEL=1
lib_deps =
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.15
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library@^1.1.2
    mikalhart/TinyGPSPlus@^1.1.0

