"""Export fitted binary scikit-learn Random Forests as dependency-free C++."""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import _tree


def _number(value: float) -> str:
    if not np.isfinite(value):
        raise ValueError(f"Cannot export non-finite value: {value}")
    literal = f"{float(value):.9g}"
    if "." not in literal and "e" not in literal.lower():
        literal += ".0"
    return f"{literal}F"


def _emit_node(tree, node: int, positive_index: int, indent: str) -> list[str]:
    feature = int(tree.feature[node])
    if feature == _tree.TREE_UNDEFINED:
        values = np.asarray(tree.value[node][0], dtype=float)
        total = float(values.sum())
        probability = float(values[positive_index] / total) if total > 0 else 0.0
        return [f"{indent}return {_number(probability)};"]

    threshold = _number(float(tree.threshold[node]))
    lines = [f"{indent}if (x[{feature}] <= {threshold}) {{"]
    lines.extend(
        _emit_node(tree, int(tree.children_left[node]), positive_index, indent + "  ")
    )
    lines.append(f"{indent}}} else {{")
    lines.extend(
        _emit_node(tree, int(tree.children_right[node]), positive_index, indent + "  ")
    )
    lines.append(f"{indent}}}")
    return lines


def _emit_forest(
    name: str,
    model: RandomForestClassifier,
    features: list[str],
    medians: Iterable[float],
    threshold: float,
) -> list[str]:
    classes = list(model.classes_)
    if 1 not in classes:
        raise ValueError(f"{name} model does not contain positive class 1")
    positive_index = classes.index(1)
    upper = name.upper()
    medians = list(medians)
    if len(medians) != len(features):
        raise ValueError(f"{name} feature/median count mismatch")

    lines = [
        f"inline constexpr size_t {upper}_FEATURE_COUNT = {len(features)};",
        f"inline constexpr float {upper}_THRESHOLD = {_number(threshold)};",
        f"inline constexpr float {upper}_IMPUTE[{upper}_FEATURE_COUNT] = {{",
        "    " + ", ".join(_number(value) for value in medians),
        "};",
        "",
    ]
    for index, estimator in enumerate(model.estimators_):
        lines.append(f"static inline float {name}_tree_{index}(const float* x) {{")
        lines.extend(_emit_node(estimator.tree_, 0, positive_index, "  "))
        lines.append("}")
        lines.append("")

    lines.extend(
        [
            f"static inline float predict_{name}_probability(const float* raw) {{",
            f"  float x[{upper}_FEATURE_COUNT];",
            f"  for (size_t i = 0; i < {upper}_FEATURE_COUNT; ++i) {{",
            f"    x[i] = finiteValue(raw[i]) ? raw[i] : {upper}_IMPUTE[i];",
            "  }",
            "  float probability = 0.0F;",
        ]
    )
    for index in range(len(model.estimators_)):
        lines.append(f"  probability += {name}_tree_{index}(x);")
    lines.extend(
        [
            f"  return probability / {_number(float(len(model.estimators_)))};",
            "}",
            "",
        ]
    )
    return lines


def export_models_to_header(
    output_path: str | Path,
    fall_model: RandomForestClassifier,
    fall_features: list[str],
    fall_medians: Iterable[float],
    fall_threshold: float,
    health_model: RandomForestClassifier,
    health_features: list[str],
    health_medians: Iterable[float],
    health_threshold: float,
) -> Path:
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by ml/train_models.py. Do not edit manually.",
        "// Models were trained only on synthetic feature data.",
        "#pragma once",
        "",
        "#include <math.h>",
        "#include <stddef.h>",
        "",
        "namespace alerta_model {",
        "",
        "static inline bool finiteValue(float value) {",
        "  return value == value && value != INFINITY && value != -INFINITY;",
        "}",
        "",
    ]
    lines.extend(
        _emit_forest(
            "fall", fall_model, fall_features, fall_medians, fall_threshold
        )
    )
    lines.extend(
        _emit_forest(
            "health", health_model, health_features, health_medians, health_threshold
        )
    )
    lines.append("}  // namespace alerta_model")
    lines.append("")
    output.write_text("\n".join(lines), encoding="utf-8")
    return output
